name: Build and Publish Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build container
        run: nix build '.#container'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load image to Docker
        run: docker load < result

      - name: Tag image for GitHub Container Registry
        run: docker tag thoughts-and-tea:latest ghcr.io/${{ github.repository_owner }}/thoughts-and-tea:latest

      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/thoughts-and-tea:latest

      - name: Tag with commit SHA
        if: github.event_name != 'pull_request'
        run: |
          docker tag thoughts-and-tea:latest ghcr.io/${{ github.repository_owner }}/thoughts-and-tea:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/thoughts-and-tea:${{ github.sha }}